### ISSUE TITLE
python3-saml-django vs python3-saml w/ django

### ISSUE THREAD

**Issue by eljeffeg** [penn-state-dance-marathon/python3-saml-django#29]
python3-saml [offers a demo](https://github.com/SAML-Toolkits/python3-saml/tree/master/demo-django) in their repository.  I'm trying to understand what the python3-saml-django overlay provides as a comparison.  I'm migrating an app from using `include('django.contrib.auth.urls'))` and this appears that it might be easier, but trying to understand the difference.  Like will it automatically utilize the `@login_required` and such?

**Comment by ngearhart** [comment]
This repository implements the boilerplate needed for `python3-saml`. Otherwise, you will have to implement this sample code yourself. With this repository, following the steps in the README, you can add SAML authentication to your Django application - no boilerplate required. I am going to close this issue, but feel free to reopen it if this did not answer your question.

**Comment by eljeffeg** [comment]
Thanks for the explanation. I did use this in my project and is working well.
